# Generated by Django 5.2.5 on 2025-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
